from django.contrib import admin
from .models import *

admin.site.register(VendorType)
admin.site.register(VendorCategory)
admin.site.register(VendorConstitution)
admin.site.register(VendorLocation)
admin.site.register(VendorServiceType)

admin.site.register(AgentType)
admin.site.register(AgentCategory)
admin.site.register(AgentLevel)
admin.site.register(AgentConstitution)
admin.site.register(AgentLocation)
admin.site.register(AgentServiceType)
admin.site.register(AgentResponsibility)

admin.site.register(ClientCategory)
admin.site.register(ClientType)
admin.site.register(ClientConstitution)
admin.site.register(ClientRole)
admin.site.register(Industry)
admin.site.register(Sector)
admin.site.register(ApplicantType)
admin.site.register(EmploymentType)
admin.site.register(EmploymentCategory)
admin.site.register(Employer)
admin.site.register(Qualification)
admin.site.register(OccupationType)
admin.site.register(Occupation)
admin.site.register(ModeOfOccupation)
admin.site.register(Institution)
admin.site.register(MembershipType)
admin.site.register(GenderSalutation)
admin.site.register(Relationship)
admin.site.register(AddressType)
admin.site.register(Ownership)
admin.site.register(EmployeeQuota)
admin.site.register(GroupLoan)
